# Generated by Django 3.2.16 on 2023-01-21 19:27

import accounting.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, validators=[accounting.models.non_empty_validator])),
                ('prefix', models.CharField(max_length=4, unique=True, validators=[accounting.models.non_empty_validator])),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(db_index=True, max_length=32, unique=True, validators=[accounting.models.non_empty_validator]),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=256, validators=[accounting.models.non_empty_validator]),
        ),
        migrations.AlterField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounting.account'),
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(editable=False, max_length=12)),
                ('voucher_date', models.DateField()),
                ('description', models.TextField()),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voucher_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.vouchertype')),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=6, max_digits=30, validators=[accounting.models.non_zero_validator])),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounting.account')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledgers', to='accounting.voucher')),
            ],
        ),
    ]
