# Generated by Django 3.2.16 on 2023-01-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_voucher_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger',
            name='status',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
